dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

before_script:
  - BOOK_BUILD_DIR="${TRAVIS_BUILD_DIR}"/_book

script:
  - npm run build

after_success:
    - |
        if [[ "${TRAVIS_BRANCH}" == master && "${TRAVIS_PULL_REQUEST}" == false ]]; then
            # Commits to master that are not pull requests, that is, only
            # actual addition of code to master, should deploy the book to
            # the site.
            bash "${TRAVIS_BUILD_DIR}"/tools/deploy/update_site_travis.bash
        fi
