dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

before_script:
  - mkdir -p "${TRAVIS_BUILD_DIR}"/build
  - CHANGED_FILES=$(git diff --name-only HEAD~1...HEAD .)
  - |
      if echo $CHANGED_FILES | grep "package.json"
      then
        cp package.json "${TRAVIS_BUILD_DIR}"/build
      fi

script:
  - |
      if echo $CHANGED_FILES | grep "package.json"
      then
        npm build --reload . ${TRAVIS_BUILD_DIR}/build
      else
        npm build . ${TRAVIS_BUILD_DIR}/build
      fi

after_success:
    - |
        if [[ "${TRAVIS_BRANCH}" == master && "${TRAVIS_PULL_REQUEST}" == false ]]; then
            # Commits to master that are not pull requests, that is, only
            # actual addition of code to master, should deploy the book to
            # the site.
            bash "${TRAVIS_BUILD_DIR}"/tools/deploy/update_site_travis.bash
        fi
