dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

install:
  - npm install

before_script:
  - mkdir -p "${TRAVIS_BUILD_DIR}"/build

script:
  - env | sort
  - npm build . "${TRAVIS_BUILD_DIR}"/build

after_success:
    - |
        if [[ "${TRAVIS_BRANCH}" == master && "${TRAVIS_PULL_REQUEST}" == false ]]; then
            # Commits to master that are not pull requests, that is, only
            # actual addition of code to master, should deploy the book to
            # the site.
            bash "${TRAVIS_BUILD_DIR}"/tools/deploy/update_site_travis.bash
        fi
