/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cb/algorithm-archive/contents/thomas_algorithm/code/nim/nimcache/thomas_algorithm.o /home/cb/algorithm-archive/contents/thomas_algorithm/code/nim/nimcache/thomas_algorithm.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwthomas_algorithm)(NF* x, NF y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAw_2thomas_algorithm)(NF* x, NF y);
N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, thomas_algorithm_iFpmS9anNHmUarPurIWrQZA)(tySequence_Zj5xKXgsXnI4n4hPS6nACA* a, tySequence_Zj5xKXgsXnI4n4hPS6nACA* b, tySequence_Zj5xKXgsXnI4n4hPS6nACA* c_in, tySequence_Zj5xKXgsXnI4n4hPS6nACA* d_in);
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(void, slasheq__7kHiltrvRlcg6wSYR3CxAwsystem)(NF* x, NF y);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, thomas_algorithmDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
NI i_4v19b9blyNs6b9cKY007zPeLA;
NIM_CONST struct {
  TGenericSeq Sup;
  NF data[3];
} TM_3pjzkgRM4HAvwFQxSjef5g_9 = {{3, 3}, {0.0,
2.0000000000000000e+00,
3.0000000000000000e+00}};
NIM_CONST tySequence_Zj5xKXgsXnI4n4hPS6nACA* x_YYoJdAK69b2gjJrP3w9buSog = ((tySequence_Zj5xKXgsXnI4n4hPS6nACA*)&TM_3pjzkgRM4HAvwFQxSjef5g_9);
NIM_CONST struct {
  TGenericSeq Sup;
  NF data[3];
} TM_3pjzkgRM4HAvwFQxSjef5g_10 = {{3, 3}, {1.0000000000000000e+00,
3.0000000000000000e+00,
6.0000000000000000e+00}};
NIM_CONST tySequence_Zj5xKXgsXnI4n4hPS6nACA* y_Wl32RauZtKsCUynxovkk0Q = ((tySequence_Zj5xKXgsXnI4n4hPS6nACA*)&TM_3pjzkgRM4HAvwFQxSjef5g_10);
NIM_CONST struct {
  TGenericSeq Sup;
  NF data[3];
} TM_3pjzkgRM4HAvwFQxSjef5g_11 = {{3, 3}, {4.0000000000000000e+00,
5.0000000000000000e+00,
0.0}};
NIM_CONST tySequence_Zj5xKXgsXnI4n4hPS6nACA* z_43gbFC3qm29cpwAm9bretKsQ = ((tySequence_Zj5xKXgsXnI4n4hPS6nACA*)&TM_3pjzkgRM4HAvwFQxSjef5g_11);
NIM_CONST struct {
  TGenericSeq Sup;
  NF data[3];
} TM_3pjzkgRM4HAvwFQxSjef5g_12 = {{3, 3}, {7.0000000000000000e+00,
5.0000000000000000e+00,
3.0000000000000000e+00}};
NIM_CONST tySequence_Zj5xKXgsXnI4n4hPS6nACA* w_IE1sETz85ruFJjHLlb9cudQ = ((tySequence_Zj5xKXgsXnI4n4hPS6nACA*)&TM_3pjzkgRM4HAvwFQxSjef5g_12);
STRING_LITERAL(TM_3pjzkgRM4HAvwFQxSjef5g_13, "The system,", 11);
STRING_LITERAL(TM_3pjzkgRM4HAvwFQxSjef5g_14, "[1.0 4.0 0.0][x] = [7.0]", 24);
STRING_LITERAL(TM_3pjzkgRM4HAvwFQxSjef5g_15, "[2.0 3.0 5.0][y] = [5.0]", 24);
STRING_LITERAL(TM_3pjzkgRM4HAvwFQxSjef5g_16, "[0.0 3.0 6.0][z] = [3.0]", 24);
STRING_LITERAL(TM_3pjzkgRM4HAvwFQxSjef5g_17, "has the solution:", 17);
NIM_CONST struct {
  TGenericSeq Sup;
  NF data[3];
} TM_3pjzkgRM4HAvwFQxSjef5g_18 = {{3, 3}, {8.6666666666666714e-01,
1.5333333333333332e+00,
-2.6666666666666672e-01}};
NIM_CONST tySequence_Zj5xKXgsXnI4n4hPS6nACA* soln_pEPHkUedplhC3rtPbe6XhQ = ((tySequence_Zj5xKXgsXnI4n4hPS6nACA*)&TM_3pjzkgRM4HAvwFQxSjef5g_18);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwthomas_algorithm)(NF* x, NF y) {
	nimfr_("*=", "system.nim");
	nimln_(3544, "system.nim");
	(*x) = ((NF)((*x)) * (NF)(y));
	popFrame();
}

static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAw_2thomas_algorithm)(NF* x, NF y) {
	nimfr_("-=", "system.nim");
	nimln_(3539, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* a;
	NI T1_;
	a = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)p;
	T1_ = (NI)0;
}

static N_INLINE(void, slasheq__7kHiltrvRlcg6wSYR3CxAwsystem)(NF* x, NF y) {
	nimfr_("/=", "system.nim");
	nimln_(3548, "system.nim");
	(*x) = ((NF)((*x)) / (NF)(y));
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, thomas_algorithm_iFpmS9anNHmUarPurIWrQZA)(tySequence_Zj5xKXgsXnI4n4hPS6nACA* a, tySequence_Zj5xKXgsXnI4n4hPS6nACA* b, tySequence_Zj5xKXgsXnI4n4hPS6nACA* c_in, tySequence_Zj5xKXgsXnI4n4hPS6nACA* d_in) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	NI n;
	NI T1_;
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* c;
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* d;
	nimfr_("thomas_algorithm", "thomas_algorithm.nim");
{	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	nimln_(3, "thomas_algorithm.nim");
	T1_ = (d_in ? d_in->Sup.len : 0);
	n = T1_;
	nimln_(5, "thomas_algorithm.nim");
	genericSeqAssign((&c), c_in, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
	nimln_(6, "thomas_algorithm.nim");
	genericSeqAssign((&d), d_in, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
	nimln_(8, "thomas_algorithm.nim");
	if ((NU)(((NI) 0)) >= (NU)(c->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)(b->Sup.len)) raiseIndexError();
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&c->data[((NI) 0)]), b->data[((NI) 0)]);
	nimln_(9, "thomas_algorithm.nim");
	if ((NU)(((NI) 0)) >= (NU)(d->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)(b->Sup.len)) raiseIndexError();
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&d->data[((NI) 0)]), b->data[((NI) 0)]);
	{
		NI i;
		NI colontmp_;
		NI TM_3pjzkgRM4HAvwFQxSjef5g_2;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(11, "thomas_algorithm.nim");
		TM_3pjzkgRM4HAvwFQxSjef5g_2 = subInt(n, ((NI) 1));
		colontmp_ = (NI)(TM_3pjzkgRM4HAvwFQxSjef5g_2);
		nimln_(1986, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NF scale;
				NI TM_3pjzkgRM4HAvwFQxSjef5g_3;
				NI TM_3pjzkgRM4HAvwFQxSjef5g_4;
				NI TM_3pjzkgRM4HAvwFQxSjef5g_5;
				if (!(res <= colontmp_)) goto LA4;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(12, "thomas_algorithm.nim");
				if ((NU)(i) >= (NU)(b->Sup.len)) raiseIndexError();
				TM_3pjzkgRM4HAvwFQxSjef5g_3 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TM_3pjzkgRM4HAvwFQxSjef5g_3)) >= (NU)(c->Sup.len)) raiseIndexError();
				if ((NU)(i) >= (NU)(a->Sup.len)) raiseIndexError();
				scale = ((NF)(1.0000000000000000e+00) / (NF)(((NF)(b->data[i]) - (NF)(((NF)(c->data[(NI)(TM_3pjzkgRM4HAvwFQxSjef5g_3)]) * (NF)(a->data[i]))))));
				nimln_(14, "thomas_algorithm.nim");
				if ((NU)(i) >= (NU)(c->Sup.len)) raiseIndexError();
				stareq__7kHiltrvRlcg6wSYR3CxAwthomas_algorithm((&c->data[i]), scale);
				if ((NU)(i) >= (NU)(d->Sup.len)) raiseIndexError();
				nimln_(15, "thomas_algorithm.nim");
				if ((NU)(i) >= (NU)(d->Sup.len)) raiseIndexError();
				if ((NU)(i) >= (NU)(a->Sup.len)) raiseIndexError();
				TM_3pjzkgRM4HAvwFQxSjef5g_4 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TM_3pjzkgRM4HAvwFQxSjef5g_4)) >= (NU)(d->Sup.len)) raiseIndexError();
				d->data[i] = ((NF)(((NF)(d->data[i]) - (NF)(((NF)(a->data[i]) * (NF)(d->data[(NI)(TM_3pjzkgRM4HAvwFQxSjef5g_4)]))))) * (NF)(scale));
				nimln_(1989, "system.nim");
				TM_3pjzkgRM4HAvwFQxSjef5g_5 = addInt(res, ((NI) 1));
				res = (NI)(TM_3pjzkgRM4HAvwFQxSjef5g_5);
			} LA4: ;
		}
	}
	{
		NI i_2;
		NI colontmp__2;
		NI TM_3pjzkgRM4HAvwFQxSjef5g_6;
		NI res_2;
		i_2 = (NI)0;
		colontmp__2 = (NI)0;
		nimln_(17, "thomas_algorithm.nim");
		TM_3pjzkgRM4HAvwFQxSjef5g_6 = subInt(n, ((NI) 2));
		colontmp__2 = (NI)(TM_3pjzkgRM4HAvwFQxSjef5g_6);
		nimln_(1957, "system.nim");
		res_2 = colontmp__2;
		{
			nimln_(1958, "system.nim");
			while (1) {
				NI TM_3pjzkgRM4HAvwFQxSjef5g_7;
				NI TM_3pjzkgRM4HAvwFQxSjef5g_8;
				nimln_(17, "thomas_algorithm.nim");
				if (!(((NI) 0) <= res_2)) goto LA7;
				nimln_(1959, "system.nim");
				i_2 = res_2;
				nimln_(18, "thomas_algorithm.nim");
				if ((NU)(i_2) >= (NU)(d->Sup.len)) raiseIndexError();
				if ((NU)(i_2) >= (NU)(c->Sup.len)) raiseIndexError();
				TM_3pjzkgRM4HAvwFQxSjef5g_7 = addInt(i_2, ((NI) 1));
				if ((NU)((NI)(TM_3pjzkgRM4HAvwFQxSjef5g_7)) >= (NU)(d->Sup.len)) raiseIndexError();
				minuseq__7kHiltrvRlcg6wSYR3CxAw_2thomas_algorithm((&d->data[i_2]), ((NF)(c->data[i_2]) * (NF)(d->data[(NI)(TM_3pjzkgRM4HAvwFQxSjef5g_7)])));
				nimln_(1960, "system.nim");
				TM_3pjzkgRM4HAvwFQxSjef5g_8 = subInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_3pjzkgRM4HAvwFQxSjef5g_8);
			} LA7: ;
		}
	}
	nimln_(21, "thomas_algorithm.nim");
	genericSeqAssign((&result), d, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	thomas_algorithmDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("thomas_algorithm", "thomas_algorithm.nim");
	nimln_(29, "thomas_algorithm.nim");
	printf("%s\012", ((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_13)? (((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_13))->data:"nil");
	fflush(stdout);
	nimln_(30, "thomas_algorithm.nim");
	printf("%s\012", ((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_14)? (((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_14))->data:"nil");
	fflush(stdout);
	nimln_(31, "thomas_algorithm.nim");
	printf("%s\012", ((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_15)? (((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_15))->data:"nil");
	fflush(stdout);
	nimln_(32, "thomas_algorithm.nim");
	printf("%s\012", ((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_16)? (((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_16))->data:"nil");
	fflush(stdout);
	nimln_(34, "thomas_algorithm.nim");
	printf("%s\012", ((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_17)? (((NimStringDesc*) &TM_3pjzkgRM4HAvwFQxSjef5g_17))->data:"nil");
	fflush(stdout);
	{
		NI res;
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NimStringDesc* T4_;
				NI TM_3pjzkgRM4HAvwFQxSjef5g_19;
				if (!(res <= ((NI) 2))) goto LA3;
				nimln_(1988, "system.nim");
				i_4v19b9blyNs6b9cKY007zPeLA = res;
				nimln_(39, "thomas_algorithm.nim");
				if ((NU)(i_4v19b9blyNs6b9cKY007zPeLA) >= (NU)(soln_pEPHkUedplhC3rtPbe6XhQ->Sup.len)) raiseIndexError();
				T4_ = (NimStringDesc*)0;
				T4_ = nimFloatToStr(soln_pEPHkUedplhC3rtPbe6XhQ->data[i_4v19b9blyNs6b9cKY007zPeLA]);
				printf("%s\012", T4_? (T4_)->data:"nil");
				fflush(stdout);
				nimln_(1989, "system.nim");
				TM_3pjzkgRM4HAvwFQxSjef5g_19 = addInt(res, ((NI) 1));
				res = (NI)(TM_3pjzkgRM4HAvwFQxSjef5g_19);
			} LA3: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, thomas_algorithmDatInit000)(void) {
NTI_Zj5xKXgsXnI4n4hPS6nACA_.size = sizeof(tySequence_Zj5xKXgsXnI4n4hPS6nACA*);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.kind = 24;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.flags = 2;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.marker = Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA;
}

