[package]
name = "flood_fill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"

[[bin]]
path = "./flood_fill.rs"
name = "main" 