[package]
name = "splitop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
rustfft = "5.1.1"

[[bin]]
path = "./split_op.rs"
name = "main"