Import('*')
from pathlib import Path

dirname = Path.cwd().parents[1].stem

env.rustc(f'#/build/rust/stack', '#/contents/stacks_and_queues/code/rust/Stack.rs')
env.Clean('rust', f'#/build/rust/stack.pdb')

env.rustc(f'#/build/rust/queue', '#/contents/stacks_and_queues/code/rust/Queue.rs')
env.Clean('rust', f'#/build/rust/queue.pdb')